---
- hosts: localhost

  vars:
   meraki_key: "{{ meraki_key }}"
   org_id: "{{ org_id }}"

  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'wireless') | list }}"
      register: network_id_get


    - name: SSID Settings
      cisco.meraki.networks_wireless_ssids:
        meraki_api_key: "{{  meraki_key  }}"
        networkId: "{{ filtered_networks.2.id }}"
        enabled: true
        state: present
        name: "{{ ssid_name }}"
        number: "{{ ssid_number }}"
        encryptionMode: "wpa"
        authMode: "psk"
        psk: "{{ preshared_key }}"
        wpaEncryptionMode: "WPA2 only"
        visible: "true"
        availableOnAllAps: "true"
      delegate_to: localhost
