---
- name: Get Port Info

  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.organizations_config_templates_switch_profiles_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result

    - name: Print Port Profile Info
      debug:
        msg: "{{ result }}"
