---
- name: Update VLAN Profile

  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
  
  tasks:
    - name: Update VLAN Profile
      cisco.meraki.networks_vlan_profiles:
        meraki_api_key: "{{ meraki_api_key }}"
        state: present
        networkId: "{{ network_id }}"
        iname: Default
        name: Default Profile
        vlanGroups:
        - name: named-group-1
          vlanIds: 2,5-7
        vlanNames:
        - name: test2
          vlanId: '2'
